spring:
  application:
    name: "ParkingLot"
  datasource:
    url: jdbc:mysql://localhost:3306/parkingLot_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "hjb+210907HJB"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
